spring:
  datasource:
    url: jdbc:mysql://locatlhost:3306/test
    username: shark_dev
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/